# Spawn an area effect cloud for each chest
# decrease the number generated by one each stand
execute as @e[tag=mapActive] at @s if score $precDesertStand desertInfo > $Zero desertInfo run summon armor_stand ~ ~ ~ {Tags:["Chest"],Invisible:1b,CustomName:"{\"text\":\"$\",\"color\":\"yellow\",\"extra\":[{\"score\":{\"objective\":\"difTracker\",\"name\":\"$chestCost\"}}]}",CustomNameVisible:1b}
execute as @e[tag=mapActive] at @s if score $precDesertStand desertInfo > $Zero desertInfo run spreadplayers ~ ~ 10 50 under 255 false @e[tag=Chest,tag=!alreadySpread]
execute as @e[tag=Chest,tag=!alreadySpread] at @s if block ~ ~ ~ air if block ~ ~-1 ~ #risk_of_rain:map_blocks run setblock ~ ~ ~ chest{Lock:"bagel"}
execute as @e[tag=!alreadySpread] at @s run tag @s add alreadySpread
scoreboard players operation $precDesertStand desertInfo -= $One desertInfo 
execute as @e[tag=mapActive] at @s if score $precDesertStand desertInfo > $Zero desertInfo run function risk_of_rain:chest_placing/chest_placing